name: Simple Android Build

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Accept Android licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

    - name: Install npm dependencies
      run: npm ci

    - name: Build web app
      run: npm run build

    - name: Capacitor sync
      run: npx cap sync android

    - name: Build Android Debug APK
      working-directory: android
      run: |
        chmod +x ./gradlew
        ./gradlew assembleDebug --no-daemon

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk

    - name: Build Info
      run: |
        echo "APK Location:"
        find android -name "*.apk" -type f